#!/usr/bin/env python3
"""
Energate Morning News Agent
Fetches the latest energy market news from energate RSS feed,
generates a general overview briefing with Claude, and saves it to
~/Documents/Energate News/.
"""

import os
import sys
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
import subprocess

# ── Config ────────────────────────────────────────────────────────────────────
RSS_URL      = "https://content.energate.de/rss/energate-messenger-plus.xml"
MAX_ARTICLES = 15
OUTPUT_DIR   = os.path.expanduser("~/Documents/Energate News")
# ──────────────────────────────────────────────────────────────────────────────


def fetch_rss(url: str) -> list[dict]:
    req = urllib.request.Request(url, headers={"User-Agent": "EnergateMorningAgent/1.0"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        raw = resp.read()
    root = ET.fromstring(raw)
    channel = root.find("channel")
    articles = []
    for item in channel.findall("item")[:MAX_ARTICLES]:
        articles.append({
            "title":   (item.findtext("title") or "").strip(),
            "link":    (item.findtext("link")  or "").strip(),
            "pubDate": (item.findtext("pubDate") or "").strip(),
            "summary": (item.findtext("description") or "").strip(),
        })
    return articles


def call_claude(prompt: str, max_tokens: int = 1500) -> str:
    import anthropic
    client = anthropic.Anthropic()
    msg = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}],
    )
    return msg.content[0].text


def build_overview_prompt(articles: list[dict]) -> str:
    items_text = "\n\n".join(
        f"{i+1}. **{a['title']}** ({a['pubDate']})\n   {a['summary']}\n   {a['link']}"
        for i, a in enumerate(articles)
    )
    return f"""You are an energy markets analyst assistant.
Below are the {len(articles)} latest news items from energate messenger (German energy trade publication).

{items_text}

Produce a concise English morning briefing:
1. **Top 3 headlines** – one sentence each, highlighting market impact
2. **Key themes** – bullet list of 3-5 overarching topics across today's news
3. **Market watch** – price signals, supply/demand shifts, or regulatory moves worth tracking
4. **Quick scan** – remaining articles as a compact numbered list (title + one-line takeaway)

Be direct and analytical. Assume the reader is an energy trading professional."""


def save_report(content: str, date_str: str) -> str:
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, f"Energate_News_{date_str}.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# Energate Morning Briefing — {date_str}\n\n")
        f.write(content)
        f.write("\n\n---\n*Generated by Energate Morning News Agent*\n")
    return path


def notify_mac(title: str, message: str, path: str):
    script = f'display notification "{message}" with title "{title}" sound name "Glass"'
    subprocess.run(["osascript", "-e", script], check=False)
    subprocess.run(["open", path], check=False)


def main():
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    print(f"[Energate Agent] {date_str} — fetching RSS feed …")

    try:
        articles = fetch_rss(RSS_URL)
    except Exception as e:
        print(f"ERROR fetching RSS: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"[Energate Agent] Got {len(articles)} articles, generating briefing …")

    try:
        briefing = call_claude(build_overview_prompt(articles))
    except Exception as e:
        print(f"ERROR calling Claude API: {e}", file=sys.stderr)
        sys.exit(1)

    path = save_report(briefing, date_str)
    print(f"[Energate Agent] Saved → {path}")

    notify_mac("Energate Morning Briefing", f"{len(articles)} articles summarised", path)


if __name__ == "__main__":
    main()
